name: 每日更新 list.json

on:
  schedule:
    - cron: '0 16 * * *'  # UTC16点 == 北京时间0点
  workflow_dispatch:

jobs:
  update-list:
    runs-on: ubuntu-latest

    steps:
    - name: 检出仓库代码
      uses: actions/checkout@v3

    - name: 给二进制加执行权限并运行
      run: |
        chmod +x ./setutime/update_list
        ./setutime/update_list

    - name: 查看 list.json 内容及hash
      run: |
        ls -l ./setutime/list.json
        sha256sum ./setutime/list.json
        head -20 ./setutime/list.json

    - name: 提交并推送更新的 list.json
      working-directory: ./setutime
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add list.json
        git diff --cached --quiet || git commit -m "自动更新 list.json"
        git push
